const SIZE = {
  AVATAR: { LARGE: 44, SMALL: 20 },
  CHECKBOX: { WIDTH: 16, HEIGHT: 16 },
  DOWN_BTN: { WIDTH: 8, HEIGHT: 4 },
  DROPDOWN_BTN: { HEIGHT: 32, GAP: 7 },
  FILTER_BAR: { WIDTH: 128, GAP: 40 },
  HEADER: { HEIGHT: 94 },
  ICON: { WIDTH: 16, HEIGHT: 16 },
  INPUT: {
    LARGE: { WIDTH: 340, HEIGHT: 64 },
    MEDIUM: { WIDTH: 320, HEIGHT: 56 },
    SMALL: { WIDTH: 300, HEIGHT: 40 },
  },
  LIST_CONTAINER: {
    WIDTH: 1280,
    PADDING_LEFT: 32,
    BORDER_RADIUS: 16,
    HEADER: { HEIGHT: 64, PADDING_TOP: 18, FONT_SIZE: 16 },
    BODY: { ITEM_HEIGHT: 100, PADDING_TOP: 16 },
  },
  LOGO: { LARGE: { WIDTH: 342, HEIGHT: 72 }, MEDIUM: { WIDTH: 199, HEIGHT: 40 } },
  WIDTH: 1280,
};

export default SIZE;
